name: Linting
on:
  push:
    paths: ["**.swift"]
    branches: [main]
  pull_request:
    paths: ["**.swift"]
    branches: [main]
  workflow_dispatch:
jobs:
  linting:
    name: Linting
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
      - name: Print SwiftLint version
        run: swiftlint --version
      - name: Run SwiftLint
        run: swiftlint --strict
      - name: Download DrString
        run: curl --location --remote-name https://github.com/dduan/DrString/releases/latest/download/drstring-x86_64-apple-darwin.tar.gz
      - name: Extract DrString
        run: |
          mkdir drstring-x86_64-apple-darwin
          tar --extract --file drstring-x86_64-apple-darwin.tar.gz --directory drstring-x86_64-apple-darwin
      - name: Add DrString to $PATH
        run: echo "$GITHUB_WORKSPACE/drstring-x86_64-apple-darwin" >> $GITHUB_PATH
      - name: Print DrString version
        run: drstring --version
      - name: Run DrString
        run: drstring check --config-file .drstring.toml
